version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: GoldenTime
      MYSQL_DATABASE: db
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    ports:
      - '5000:3306'
    volumes:
      - mydb:/var/lib/mysql
volumes:
  mydb:
